development:
  adapter: postgresql
  encoding: unicode
  database: scheduler_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: scheduler_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: scheduler_prod
  pool: 5
  username: postgres
  password: postgres